//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpMvcEfOnboardProject1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductSold
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Selecting Product Name is required")]
        public int ProductId { get; set; }
        [Required(ErrorMessage = "Selecting Customer Name is required")]
        public int CustomerId { get; set; }
        [Required(ErrorMessage = "Select Store Name is required")]
        public int StoreId { get; set; }
        [Required(ErrorMessage = "Date Sold is required")]
        [DisplayName("Date Sold")]
        public System.DateTime DateSold { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}
